/** Representa o objeto de um país, possui nome, ddi e nome abreviado. */
export interface Country {
  name: string;
  dial_code: string;
  code: string;
}

/** Lista de países com o DDI. */
export const countries: Country[] = [
  { name: 'Afeganistão', dial_code: '+93', code: 'af' },
  { name: 'África do Sul', dial_code: '+27', code: 'za' },
  { name: 'Albânia', dial_code: '+355', code: 'al' },
  { name: 'Alemanha', dial_code: '+49', code: 'de' },
  { name: 'Andorra', dial_code: '+376', code: 'ad' },
  { name: 'Angola', dial_code: '+244', code: 'ao' },
  { name: 'Anguilla', dial_code: '+1', code: 'ai' },
  { name: 'Antígua e Barbuda', dial_code: '+1', code: 'ag' },
  { name: 'Arábia Saudita', dial_code: '+966', code: 'sa' },
  { name: 'Argélia', dial_code: '+213', code: 'dz' },
  { name: 'Argentina', dial_code: '+54', code: 'ar' },
  { name: 'Armênia', dial_code: '+374', code: 'am' },
  { name: 'Aruba', dial_code: '+297', code: 'aw' },
  { name: 'Austrália', dial_code: '+61', code: 'au' },
  { name: 'Áustria', dial_code: '+43', code: 'at' },
  { name: 'Azerbaijão', dial_code: '+994', code: 'az' },
  { name: 'Bahamas', dial_code: '+1', code: 'bs' },
  { name: 'Bahrein', dial_code: '+973', code: 'bh' },
  { name: 'Bangladesh', dial_code: '+880', code: 'bd' },
  { name: 'Barbados', dial_code: '+1', code: 'bb' },
  { name: 'Bélgica', dial_code: '+32', code: 'be' },
  { name: 'Belize', dial_code: '+501', code: 'bz' },
  { name: 'Benin', dial_code: '+229', code: 'bj' },
  { name: 'Bermudas', dial_code: '+1', code: 'bm' },
  { name: 'Bolívia', dial_code: '+591', code: 'bo' },
  { name: 'Bósnia e Herzegovina', dial_code: '+387', code: 'ba' },
  { name: 'Botsuana', dial_code: '+267', code: 'bw' },
  { name: 'Brasil', dial_code: '+55', code: 'br' },
  { name: 'Brunei', dial_code: '+673', code: 'bn' },
  { name: 'Bulgária', dial_code: '+359', code: 'bg' },
  { name: 'Burkina Faso', dial_code: '+226', code: 'bf' },
  { name: 'Butão', dial_code: '+975', code: 'bt' },
  { name: 'Cabo Verde', dial_code: '+238', code: 'cv' },
  { name: 'Camarões', dial_code: '+237', code: 'cm' },
  { name: 'Camboja', dial_code: '+855', code: 'kh' },
  { name: 'Canadá', dial_code: '+1', code: 'ca' },
  { name: 'Catar', dial_code: '+974', code: 'qa' },
  { name: 'Cazaquistão', dial_code: '+7', code: 'kz' },
  { name: 'Chile', dial_code: '+56', code: 'cl' },
  { name: 'China', dial_code: '+86', code: 'cn' },
  { name: 'Chipre', dial_code: '+357', code: 'cy' },
  { name: 'Colômbia', dial_code: '+57', code: 'co' },
  { name: 'Comores', dial_code: '+269', code: 'km' },
  { name: 'Congo - Brazzaville', dial_code: '+242', code: 'cg' },
  { name: 'Congo - Kinshasa', dial_code: '+243', code: 'cd' },
  { name: 'Coreia do Norte', dial_code: '+850', code: 'kp' },
  { name: 'Coreia do Sul', dial_code: '+82', code: 'kr' },
  { name: 'Costa do Marfim', dial_code: '+225', code: 'ci' },
  { name: 'Costa Rica', dial_code: '+506', code: 'cr' },
  { name: 'Croácia', dial_code: '+385', code: 'hr' },
  { name: 'Cuba', dial_code: '+53', code: 'cu' },
  { name: 'Dinamarca', dial_code: '+45', code: 'dk' },
  { name: 'Egito', dial_code: '+20', code: 'eg' },
  { name: 'El Salvador', dial_code: '+503', code: 'sv' },
  { name: 'Emirados Árabes Unidos', dial_code: '+971', code: 'ae' },
  { name: 'Equador', dial_code: '+593', code: 'ec' },
  { name: 'Eritreia', dial_code: '+291', code: 'er' },
  { name: 'Eslováquia', dial_code: '+421', code: 'sk' },
  { name: 'Eslovênia', dial_code: '+386', code: 'si' },
  { name: 'Espanha', dial_code: '+34', code: 'es' },
  { name: 'Estados Unidos', dial_code: '+1', code: 'us' },
  { name: 'Estônia', dial_code: '+372', code: 'ee' },
  { name: 'Etiópia', dial_code: '+251', code: 'et' },
  { name: 'Filipinas', dial_code: '+63', code: 'ph' },
  { name: 'Finlândia', dial_code: '+358', code: 'fi' },
  { name: 'França', dial_code: '+33', code: 'fr' },
  { name: 'Gabão', dial_code: '+241', code: 'ga' },
  { name: 'Gâmbia', dial_code: '+220', code: 'gm' },
  { name: 'Gana', dial_code: '+233', code: 'gh' },
  { name: 'Geórgia', dial_code: '+995', code: 'ge' },
  { name: 'Gibraltar', dial_code: '+350', code: 'gi' },
  { name: 'Grécia', dial_code: '+30', code: 'gr' },
  { name: 'Grenada', dial_code: '+1', code: 'gd' },
  { name: 'Guatemala', dial_code: '+502', code: 'gt' },
  { name: 'Guiana', dial_code: '+592', code: 'gy' },
  { name: 'Guiné', dial_code: '+224', code: 'gn' },
  { name: 'Guiné-Bissau', dial_code: '+245', code: 'gw' },
  { name: 'Haiti', dial_code: '+509', code: 'ht' },
  { name: 'Holanda', dial_code: '+31', code: 'nl' },
  { name: 'Honduras', dial_code: '+504', code: 'hn' },
  { name: 'Hong Kong', dial_code: '+852', code: 'hk' },
  { name: 'Hungria', dial_code: '+36', code: 'hu' },
  { name: 'Iêmen', dial_code: '+967', code: 'ye' },
  { name: 'Ilhas Maldivas', dial_code: '+960', code: 'mv' },
  { name: 'Índia', dial_code: '+91', code: 'in' },
  { name: 'Indonésia', dial_code: '+62', code: 'id' },
  { name: 'Inglaterra', dial_code: '+44', code: 'gb' },
  { name: 'Irã', dial_code: '+98', code: 'ir' },
  { name: 'Iraque', dial_code: '+964', code: 'iq' },
  { name: 'Irlanda', dial_code: '+353', code: 'ie' },
  { name: 'Islândia', dial_code: '+354', code: 'is' },
  { name: 'Israel', dial_code: '+972', code: 'il' },
  { name: 'Itália', dial_code: '+39', code: 'it' },
  { name: 'Jamaica', dial_code: '+1', code: 'jm' },
  { name: 'Japão', dial_code: '+81', code: 'jp' },
  { name: 'Jordânia', dial_code: '+962', code: 'jo' },
  { name: 'Kosovo', dial_code: '+383', code: 'xk' },
  { name: 'Kuwait', dial_code: '+965', code: 'kw' },
  { name: 'Laos', dial_code: '+856', code: 'la' },
  { name: 'Letônia', dial_code: '+371', code: 'lv' },
  { name: 'Líbano', dial_code: '+961', code: 'lb' },
  { name: 'Libéria', dial_code: '+231', code: 'lr' },
  { name: 'Líbia', dial_code: '+218', code: 'ly' },
  { name: 'Liechtenstein', dial_code: '+423', code: 'li' },
  { name: 'Lituânia', dial_code: '+370', code: 'lt' },
  { name: 'Luxemburgo', dial_code: '+352', code: 'lu' },
  { name: 'Macau', dial_code: '+853', code: 'mo' },
  { name: 'Macedônia', dial_code: '+389', code: 'mk' },
  { name: 'Madagáscar', dial_code: '+261', code: 'mg' },
  { name: 'Malásia', dial_code: '+60', code: 'my' },
  { name: 'Malawi', dial_code: '+265', code: 'mw' },
  { name: 'Mali', dial_code: '+223', code: 'ml' },
  { name: 'Malta', dial_code: '+356', code: 'mt' },
  { name: 'Marrocos', dial_code: '+212', code: 'ma' },
  { name: 'Martinica', dial_code: '+596', code: 'mq' },
  { name: 'Maurício', dial_code: '+230', code: 'mu' },
  { name: 'México', dial_code: '+52', code: 'mx' },
  { name: 'Mônaco', dial_code: '+377', code: 'mc' },
  { name: 'Mongólia', dial_code: '+976', code: 'mn' },
  { name: 'Montenegro', dial_code: '+382', code: 'me' },
  { name: 'Nepal', dial_code: '+977', code: 'np' },
  { name: 'Nicarágua', dial_code: '+505', code: 'ni' },
  { name: 'Nigéria', dial_code: '+234', code: 'ng' },
  { name: 'Noruega', dial_code: '+47', code: 'no' },
  { name: 'Nova Zelândia', dial_code: '+64', code: 'nz' },
  { name: 'Panamá', dial_code: '+507', code: 'pa' },
  { name: 'Paquistão', dial_code: '+92', code: 'pk' },
  { name: 'Paraguai', dial_code: '+595', code: 'py' },
  { name: 'Peru', dial_code: '+51', code: 'pe' },
  { name: 'Polônia', dial_code: '+48', code: 'pl' },
  { name: 'Portugal', dial_code: '+351', code: 'pt' },
  { name: 'Quênia', dial_code: '+254', code: 'ke' },
  { name: 'Reino Unido', dial_code: '+44', code: 'gb' },
  { name: 'República Checa', dial_code: '+420', code: 'cz' },
  { name: 'República Dominicana', dial_code: '+1', code: 'do' },
  { name: 'Romênia', dial_code: '+40', code: 'ro' },
  { name: 'Rússia', dial_code: '+7', code: 'ru' },
  { name: 'Senegal', dial_code: '+221', code: 'sn' },
  { name: 'Sérvia', dial_code: '+381', code: 'rs' },
  { name: 'Singapura', dial_code: '+65', code: 'sg' },
  { name: 'Síria', dial_code: '+963', code: 'sy' },
  { name: 'Suécia', dial_code: '+46', code: 'se' },
  { name: 'Suíça', dial_code: '+41', code: 'ch' },
  { name: 'Suriname', dial_code: '+597', code: 'sr' },
  { name: 'Tailândia', dial_code: '+66', code: 'th' },
  { name: 'Taiwan', dial_code: '+886', code: 'tw' },
  { name: 'Tanzânia', dial_code: '+255', code: 'tz' },
  { name: 'Tunísia', dial_code: '+216', code: 'tn' },
  { name: 'Turquia', dial_code: '+90', code: 'tr' },
  { name: 'Ucrânia', dial_code: '+380', code: 'ua' },
  { name: 'Uruguai', dial_code: '+598', code: 'uy' },
  { name: 'Uzbequistão', dial_code: '+998', code: 'uz' },
  { name: 'Vaticano', dial_code: '+379', code: 'va' },
  { name: 'Venezuela', dial_code: '+58', code: 've' },
  { name: 'Vietnã', dial_code: '+84', code: 'vn' },
  { name: 'Zâmbia', dial_code: '+260', code: 'zm' },
  { name: 'Zimbábue', dial_code: '+263', code: 'zw' },
];
